import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load environment variables
import dotenv from 'dotenv';
dotenv.config();

// Initialize Supabase client
const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('❌ Missing environment variables:');
  console.error('  SUPABASE_URL:', supabaseUrl ? '✅ Set' : '❌ Missing');
  console.error('  SUPABASE_SERVICE_ROLE_KEY:', supabaseKey ? '✅ Set' : '❌ Missing');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

console.log('🧪 Supabase Storage Test Script');
console.log('================================');
console.log(`Project URL: ${supabaseUrl}`);
console.log(`Service Key: ${supabaseKey.substring(0, 20)}...`);
console.log('');

// Test functions
async function testStorageConnection() {
  console.log('1️⃣ Testing Supabase connection...');
  
  try {
    const { data, error } = await supabase.storage.listBuckets();
    
    if (error) {
      throw error;
    }
    
    console.log('✅ Connection successful!');
    console.log(`📦 Found ${data.length} buckets:`, data.map(b => b.name));
    return true;
  } catch (error) {
    console.error('❌ Connection failed:', error.message);
    return false;
  }
}

async function createTestBucket() {
  console.log('\n2️⃣ Creating test bucket...');
  
  try {
    const bucketName = 'test-storage';
    
    // Check if bucket already exists
    const { data: existingBuckets } = await supabase.storage.listBuckets();
    const bucketExists = existingBuckets.some(b => b.name === bucketName);
    
    if (bucketExists) {
      console.log('✅ Bucket already exists, skipping creation');
      return bucketName;
    }
    
    const { data, error } = await supabase.storage.createBucket(bucketName, {
      public: true,
      fileSizeLimit: 52428800, // 50MB
      allowedMimeTypes: ['image/*', 'video/*', 'audio/*', 'text/*']
    });
    
    if (error) {
      throw error;
    }
    
    console.log('✅ Test bucket created successfully!');
    console.log('Bucket details:', data);
    return bucketName;
  } catch (error) {
    console.error('❌ Failed to create bucket:', error.message);
    return null;
  }
}

async function testFileUpload(bucketName) {
  console.log('\n3️⃣ Testing file upload...');
  
  try {
    // Create a test file
    const testContent = `This is a test file created at ${new Date().toISOString()}\nGenerated by Supabase Storage test script`;
    const testFileName = `test-${Date.now()}.txt`;
    
    // Upload the file
    const { data, error } = await supabase.storage
      .from(bucketName)
      .upload(testFileName, testContent, {
        contentType: 'text/plain',
        cacheControl: '3600',
        upsert: false
      });
    
    if (error) {
      throw error;
    }
    
    console.log('✅ File uploaded successfully!');
    console.log('File path:', data.path);
    console.log('File size:', testContent.length, 'bytes');
    
    return testFileName;
  } catch (error) {
    console.error('❌ File upload failed:', error.message);
    return null;
  }
}

async function testFileDownload(bucketName, fileName) {
  console.log('\n4️⃣ Testing file download...');
  
  try {
    const { data, error } = await supabase.storage
      .from(bucketName)
      .download(fileName);
    
    if (error) {
      throw error;
    }
    
    const content = await data.text();
    console.log('✅ File downloaded successfully!');
    console.log('Downloaded content:', content.substring(0, 100) + '...');
    
    return true;
  } catch (error) {
    console.error('❌ File download failed:', error.message);
    return false;
  }
}

async function testPublicURL(bucketName, fileName) {
  console.log('\n5️⃣ Testing public URL access...');
  
  try {
    const { data } = supabase.storage
      .from(bucketName)
      .getPublicUrl(fileName);
    
    const publicUrl = data.publicUrl;
    console.log('✅ Public URL generated:', publicUrl);
    
    // Test if the URL is accessible
    const response = await fetch(publicUrl);
    if (response.ok) {
      console.log('✅ Public URL is accessible!');
      console.log('Response status:', response.status);
      console.log('Content type:', response.headers.get('content-type'));
    } else {
      console.log('⚠️ Public URL returned status:', response.status);
    }
    
    return publicUrl;
  } catch (error) {
    console.error('❌ Public URL test failed:', error.message);
    return null;
  }
}

async function testImageUpload(bucketName) {
  console.log('\n6️⃣ Testing image upload (simulating Replicate output)...');
  
  try {
    // Create a simple test image (base64 data URI)
    const testImageData = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0iIzAwZmYiLz48dGV4dCB4PSI1MCIgeT0iNTAiIGZvbnQtZmFtaWx5PSJBcmlhbCIgZm9udC1zaXplPSIxNCIgZmlsbD0id2hpdGUiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuM2VtIj5UZXN0PC90ZXh0Pjwvc3ZnPg==';
    
    const imageFileName = `test-image-${Date.now()}.svg`;
    
    // Convert base64 to buffer
    const base64Data = testImageData.split(',')[1];
    const buffer = Buffer.from(base64Data, 'base64');
    
    const { data, error } = await supabase.storage
      .from(bucketName)
      .upload(imageFileName, buffer, {
        contentType: 'image/svg+xml',
        cacheControl: '31536000', // 1 year
        upsert: false
      });
    
    if (error) {
      throw error;
    }
    
    console.log('✅ Test image uploaded successfully!');
    console.log('Image path:', data.path);
    console.log('Image size:', buffer.length, 'bytes');
    
    return imageFileName;
  } catch (error) {
    console.error('❌ Image upload failed:', error.message);
    return null;
  }
}

async function testFolderStructure(bucketName) {
  console.log('\n7️⃣ Testing folder structure (simulating pipeline)...');
  
  try {
    const folders = ['images', 'videos', 'audio', 'final'];
    const uploadedFiles = [];
    
    for (const folder of folders) {
      const fileName = `${folder}/test-${Date.now()}.txt`;
      const content = `Test file in ${folder} folder - ${new Date().toISOString()}`;
      
      const { data, error } = await supabase.storage
        .from(bucketName)
        .upload(fileName, content, {
          contentType: 'text/plain',
          cacheControl: '3600',
          upsert: false
        });
      
      if (error) {
        console.error(`❌ Failed to upload to ${folder}:`, error.message);
        continue;
      }
      
      console.log(`✅ Created ${folder}/test.txt`);
      uploadedFiles.push(fileName);
    }
    
    // List files in bucket
    const { data: files, error } = await supabase.storage
      .from(bucketName)
      .list('', {
        limit: 100,
        offset: 0
      });
    
    if (error) {
      throw error;
    }
    
    console.log('\n📁 Current bucket structure:');
    files.forEach(file => {
      const size = file.metadata?.size || 'unknown';
      const updated = file.updated_at ? new Date(file.updated_at).toLocaleString() : 'unknown';
      console.log(`  ${file.name} (${size} bytes, updated: ${updated})`);
    });
    
    return uploadedFiles;
  } catch (error) {
    console.error('❌ Folder structure test failed:', error.message);
    return [];
  }
}

async function cleanupTestFiles(bucketName, fileNames) {
  console.log('\n8️⃣ Cleaning up test files...');
  
  try {
    if (fileNames.length === 0) {
      console.log('ℹ️ No files to clean up');
      return;
    }
    
    const { error } = await supabase.storage
      .from(bucketName)
      .remove(fileNames);
    
    if (error) {
      throw error;
    }
    
    console.log(`✅ Cleaned up ${fileNames.length} test files`);
  } catch (error) {
    console.error('❌ Cleanup failed:', error.message);
  }
}

async function testStoragePolicies() {
  console.log('\n9️⃣ Testing storage policies...');
  
  try {
    // Test public read access
    const { data: buckets } = await supabase.storage.listBuckets();
    const publicBucket = buckets.find(b => b.public);
    
    if (publicBucket) {
      console.log(`✅ Found public bucket: ${publicBucket.name}`);
      
      // Test if we can list files without authentication
      const publicClient = createClient(supabaseUrl, process.env.SUPABASE_ANON_KEY);
      const { data: publicFiles, error: publicError } = await publicClient.storage
        .from(publicBucket.name)
        .list('', { limit: 10 });
      
      if (publicError) {
        console.log('⚠️ Public access test failed:', publicError.message);
      } else {
        console.log(`✅ Public access working - can list ${publicFiles.length} files`);
      }
    } else {
      console.log('ℹ️ No public buckets found');
    }
    
  } catch (error) {
    console.error('❌ Policy test failed:', error.message);
  }
}

// Main test execution
async function runAllTests() {
  console.log('🚀 Starting comprehensive storage tests...\n');
  
  try {
    // Test 1: Connection
    const connectionOk = await testStorageConnection();
    if (!connectionOk) {
      console.error('❌ Cannot proceed without connection');
      return;
    }
    
    // Test 2: Create bucket
    const bucketName = await createTestBucket();
    if (!bucketName) {
      console.error('❌ Cannot proceed without bucket');
      return;
    }
    
    // Test 3: File upload
    const testFileName = await testFileUpload(bucketName);
    if (!testFileName) {
      console.error('❌ Cannot proceed without file upload');
      return;
    }
    
    // Test 4: File download
    const downloadOk = await testFileDownload(bucketName, testFileName);
    
    // Test 5: Public URL
    const publicUrl = await testPublicURL(bucketName, testFileName);
    
    // Test 6: Image upload
    const imageFileName = await testImageUpload(bucketName);
    
    // Test 7: Folder structure
    const uploadedFiles = await testFolderStructure(bucketName);
    
    // Test 8: Storage policies
    await testStoragePolicies();
    
    // Test 9: Cleanup
    const allFiles = [testFileName, imageFileName, ...uploadedFiles].filter(Boolean);
    await cleanupTestFiles(bucketName, allFiles);
    
    console.log('\n🎉 All tests completed!');
    console.log('================================');
    console.log('✅ Storage connection: Working');
    console.log('✅ Bucket creation: Working');
    console.log('✅ File upload: Working');
    console.log('✅ File download: Working');
    console.log('✅ Public URLs: Working');
    console.log('✅ Image handling: Working');
    console.log('✅ Folder structure: Working');
    console.log('✅ Storage policies: Working');
    console.log('✅ Cleanup: Working');
    console.log('\n🚀 Your Supabase Storage is ready for the pipeline!');
    
  } catch (error) {
    console.error('\n💥 Test execution failed:', error);
    console.error('Please check your configuration and try again.');
  }
}

// Run tests if this file is executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  runAllTests();
}

export {
  testStorageConnection,
  createTestBucket,
  testFileUpload,
  testFileDownload,
  testPublicURL,
  testImageUpload,
  testFolderStructure,
  cleanupTestFiles,
  testStoragePolicies
};


